### ISSUE TITLE
Calendar does not fully display task

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-M11-2/main#145] opened 2019-04-04 13:36 UTC
**Describe the bug**
I have 3 task which falls on the same day but the calendar is unable to display all 3.

**To Reproduce**
1. add multiple different task on the same day and observe when the calendar does not fit everything

**Expected behavior**
I expected all my task to be able to be seen 
**Screenshots**
![image](https://user-images.githubusercontent.com/46835688/55454114-324f4780-5611-11e9-9960-9e94ef986d10.png)

<hr>

**Reported by:** @arhjaye
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#141]</sub>

**Comment by Justin-Ong** [comment] 2019-04-04 15:04
The calendar cell is scrollable. Unable to reproduce bug in testing.

Will consider UI changes to emphasise that calendar cells are scrollable.

**Comment by Justin-Ong** [comment] 2019-04-04 16:11
Addressed in PR #152.

**Closed as completed by Justin-Ong** 2019-04-04 16:11 UTC
Labels: priority.Low, type.Bug, v1.4, severity.Low
